# Generated by Django 3.2.6 on 2021-08-31 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0001_initial'),
        ('core', '0005_pontos_turisticos_avalicoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontos_turisticos',
            name='enderecos',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='enderecos.endereco'),
            preserve_default=False,
        ),
    ]
