# Generated by Django 3.2.6 on 2021-08-31 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0001_initial'),
        ('core', '0006_pontos_turisticos_enderecos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontos_turisticos',
            name='enderecos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enderecos.endereco'),
        ),
    ]
