# Generated by Django 3.2.6 on 2021-09-03 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_pontos_turisticos_enderecos'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontos_turisticos',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='pontos_turiscos'),
        ),
    ]
